repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^examples/
      - id: end-of-file-fixer
        exclude: ^examples/
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/mwouts/jupytext
    rev: v1.16.7
    hooks:
      - id: jupytext
        args: [--sync]
        files: ^examples/.*\.ipynb$
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
        args: [ --fix ]
        exclude: ^examples/.*\.py$
      - id: ruff-format
        exclude: ^examples/.*\.py$

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.11.3
    hooks:
      # Update the requirements.txt if pyproject.toml changes
      - id: uv-export
        args: ["--frozen", "--output-file=requirements.txt", "--quiet"]
      - id: uv-lock
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true

      - id: mypy
        name: mypy
        entry: uv run mypy .
        language: system
        types: [python]
        pass_filenames: false
        exclude: ^examples/.*\.py$
