repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^examples/
      - id: end-of-file-fixer
        exclude: ^examples/
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        name: Run Ruff on Notebooks
        args: [--fix]
        additional_dependencies: [ruff]
      - id: nbqa-ruff-format
        name: Format Notebooks with Ruff
        additional_dependencies: [ruff]

  - repo: https://github.com/mwouts/jupytext
    rev: v1.16.1
    hooks:
      - id: jupytext
        name: Generate Python scripts from notebooks
        args: [--to, "py:percent"]
        types: [jupyter]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
        args: [ --fix , --unsafe-fixes ]
        exclude: ^examples/
      - id: ruff-format
        exclude: ^examples/

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.3
    hooks:
      - id: uv-export
        args: ["--frozen", "--output-file=requirements.txt", "--quiet"]
      - id: uv-lock

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest tests/
        language: system
        pass_filenames: false
        always_run: true

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: true
        exclude: ^examples/

      - id: test-notebooks
        name: Test Jupyter Notebook Execution
        entry: uv run pytest --nbmake
        language: system
        types: [jupyter]
        always_run: true
